### PR TITLE
[Form Validation] fix "disabled" detection

### LINKED ISSUE #1345: [Form Validation] should not validate fields inside `fieldset[disabled] `
Any fields inside `fieldset[disabled]` should be disabled: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#attr-disabled

Currently, the code only checks field props whether it's disabled:
```js
            var isDisabled = true;
            $.each($field, function(){
                if(!$(this).prop('disabled')) {
                  isDisabled = false;
                  return false;
                }
            });
```

It should check `:disabled` with jQuery (IE and old Edge cannot handle native `:disabled` selector properly): https://api.jquery.com/disabled-selector/

Test Case:
https://codepen.io/jamesjav/pen/ZEGOMWO

`baz` is under `fieldset[disabled]` so it should not prevent submitting the form

### PR DESCRIPTION
**Pull request by jameschenjav**
Currently, the code to detect a field is `disabled` cannot handle fields under `fieldset[disabled]`

## Description
Properly detect `disabled` with jQuery `:disabled` selector

## Testcase
https://codepen.io/jamesjav/pen/ZEGOMWO

Click "Validate" button, "baz" field should not have error since it won't be in form data.

> edited: added a test case from @lubber-de for radio buttons with first one disabled

## Closes
#1345

### CODE REVIEW

**Comment by VanquishedWombat** [comment]
Question - what is the use-case for when I would want a disabled field, where I cannot enter data, to be validated in form validation? Since I cannot enter data into the disabled field then I cannot fix the failed validation situation. I may be missing something but IMHO this would not be great UX ? I'm probably missing something.

**Comment by jameschenjav** [comment]
Hi @VanquishedWombat 
For example, payment needs to be made, and a few options are available. So each of the methods is assigned to a `<fieldset>` that contains several fields with different rules. Depends on the selection, simply toggle `disabled` and show/hide the fieldsets.

**Comment by prudho** [comment]
`fieldset` isn't handled by fomantic actually. But you can also surround grouped fields with class `disabled fields` and it should work.

**Comment by jameschenjav** [comment]
> `fieldset` isn't handled by fomantic actually. But you can also surround grouped fields with class `disabled fields` and it should work.

Hi @prudho 
not sure following you, but i changed my test case to `fieldset.disabled.fields[disabled]`

File: src/definitions/behaviors/form.js [hunk 1]
```diff
@@ -1207,13 +1207,7 @@ $.fn.form = function(parameters) {
...
               field.identifier = identifier;
             }
-            var isDisabled = true;
-            $.each($field, function(){
-                if(!$(this).prop('disabled')) {
-                  isDisabled = false;
-                  return false;
-                }
-            });
+            var isDisabled = $field.is(':disabled');
```
Comment (prudho) [inline src/definitions/behaviors/form.js]: This line doesn't work properly when a field has multiple input. Example:
```html
<fieldset class="disabled grouped fields" disabled>
  <label>Bananaaaaa</label>
  <div class="field">
    <div class="ui checkbox">
      <input type="checkbox" name="fruit" tabindex="0" class="hidden">
      <label>Apples</label>
    </div>
  </div>
  <div class="field">
    <div class="ui checkbox checkbox">
      <input type="checkbox" name="fruit" tabindex="0" class="hidden">
      <label>Oranges</label>
    </div>
  </div>
  <div class="field">
    <div class="ui checkbox checkbox">
      <input type="checkbox" name="fruit" tabindex="0" class="hidden">
      <label>Pears</label>
    </div>
  </div>
  <div class="field">
    <div class="ui checkbox checkbox">
      <input type="checkbox" name="fruit" tabindex="0" class="hidden">
      <label>Grapefruit</label>
    </div>
  </div>
</fieldset>
```

Comment (lubber-de) [reply src/definitions/behaviors/form.js]: Yes,  we added that field loop because otherwise radio groups were not valiadated if the first one was disabled. https://github.com/fomantic/Fomantic-UI/pull/372
So there was a reason why each field has to be checked separately

Comment (jameschenjav) [reply src/definitions/behaviors/form.js]: @prudho i still don't understand what's your "work" means. all fields inside `fieldset[disabled]` are disabled [by design](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#attr-disabled). jquery [`:disabled` selector](https://api.jquery.com/disabled-selector/) works properly [even in IE](https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled#Browser_compatibility), while `prop('disabled')` cannot handle this case.

@lubber-de updated PR and added your test case in my demo

Comment (prudho) [reply src/definitions/behaviors/form.js]: @jameschenjav sorry i was mistaken there :/ I supposed that validation was testing an eventual `disabled` class for field groups, which isn't the case here.

File: src/definitions/behaviors/form.js [hunk 2]
```diff
@@ -1207,13 +1207,7 @@ $.fn.form = function(parameters) {
...
               field.identifier = identifier;
             }
-            var isDisabled = true;
-            $.each($field, function(){
-                if(!$(this).prop('disabled')) {
-                  isDisabled = false;
-                  return false;
-                }
-            });
+            var isDisabled = !$field.filter(':not(:disabled):first').length;
```
Comment (lubber-de) [inline src/definitions/behaviors/form.js]: The `:first` selector does not seem to be necessary . It is also [deprecated as of Jquery 3.4](https://api.jquery.com/first-selector/).

Comment (jameschenjav) [reply src/definitions/behaviors/form.js]: ok i will remove it. thought it's faster

**Comment by lubber-de** [comment]
@all-contributors please add @jameschenjav for code
