### PR TITLE
fix(dropdown) - forceSelection trigger event with null addition

### LINKED ISSUE #1679: [Dropdown] JavaScript error when adding to dropdwon while hideAdditions = false
# Bug Report
when allowAdditions is true and  hideAdditions is  false , Javascript error occurs when clicking the new added label

## Steps to reproduce
1. create a new dropdown with options `{ allowAdditions: true, hideAdditions: false}`
2. add a new option
3. click the new added option
4. see the error 

## Expected result
shouldn't get an error

## Actual result
 Uncaught TypeError: Cannot read property 'trim' of undefined

## Testcase
http://jsfiddle.net/kamalkemo/bwhsrvdf/

## Version
2.8.7

### PR DESCRIPTION
**Pull request by TheJltres**
## Description
Hi!
This fix is very simple,  when `allowAdditions` is handled by click event, `forceSelection` triggers event click again, but with `allowAdditions` removed can't find the item.
As far as I know I can't know if the event calling this method is the original click or `forceSelection` trigger, so what I did is: if there's no element and `allowAdditions` and `forceSelection` is set to true return `null`.

## Testcase
- Add a non existing value to the dropdown
- Watch console

## Broken
A JS error occurs `Cannot read property 'trim' of undefined`
http://jsfiddle.net/kamalkemo/bwhsrvdf/

## Fixed
No error anymore
http://jsfiddle.net/lubber/sqpc9d1y/

## Closes
#1679

### CODE REVIEW

**Comment by kamalkemo** [comment]
This doesn't work as expected

value is removed when clicked

**Comment by TheJltres** [comment]
Okey, sorry, wrong commit 🤦, that doesn't make sense.

**Comment by TheJltres** [comment]
As you can see now it handles well the click and no error is trowed, thanks for your patience

**Comment by TheJltres** [comment]
Now that it works I want to get a hint from maintainers, there is another way to prevent this, and is inside force selection, if 'allowAdditions' is enabled and there is no item, don't trigger click event.

I would like to discuss this for a better fix.

File: src/definitions/modules/dropdown.js [hunk 1]
```diff
@@ -1942,12 +1942,16 @@ $.fn.dropdown = function(parameters) {
                 $choice.find(selector.menu).remove();
                 $choice.find(selector.menuIcon).remove();
               }
-              return ($choice.data(metadata.text) !== undefined)
```
Comment (ko2in) [inline src/definitions/modules/dropdown.js:1945]: Only two minor changes here would fix the same instead of 10 new lines.
```
return ($choice.data(metadata.text) !== undefined)
  ? $choice.data(metadata.text)
  : (preserveHTML)
    ? $choice.html() && $choice.html().trim()
    : $choice.text() && $choice.text().trim()
;
```

Comment (TheJltres) [reply src/definitions/modules/dropdown.js:1945]: Okey, no problem!

**Review by ko2in — APPROVED** [review]
LGTM. :+1:

**Review by lubber-de — APPROVED** [review]
LGTM. I added a testcase jsfiddle to your PR description. Please try to create a testcase yourself whenever providing a PR. Makes it easier for maintainers to review and increases chances to get things merged quicker 😉

**Comment by TheJltres** [comment]
> LGTM. I added a testcase jsfiddle to your PR description. Please try to create a testcase yourself whenever providing a PR. Makes it easier for maintainers to review and increases chances to get things merged quicker 😉

I didn't know how to, now that i saw your jsfiddle i will do it next time. Thanks!
