### PR TITLE
fix(modal): vertical alignment on detachable modal was incorrect

### LINKED ISSUE #1009: Modal not centered correctly when using detachable: false
# Bug Report

Hello, it seems that the modal is not centering correctly when using option detachable: false and we have a long scrollable content.

My guess is that it is not calculating the top property correctly, it seems to be using the body height instead of viewport height.

Note 1: If you remove detachable : false option it works.
Note 2: If you remove like a paragraph of text you will then see the modal, but it won't be centered though.

## Steps to reproduce
1. Open the fiddle and click on show modal button

## Expected result
Modal should be centered.

## Actual result
Modal is not centered. 

## Testcase
[jsFiddle link](http://jsfiddle.net/7j38xdbw/1/)

My original Semantic-ui repository issue [link](https://github.com/Semantic-Org/Semantic-UI/issues/6866)

## Version
2.7.8

### PR DESCRIPTION
**Pull request by prudho**
## Description
First, i'm not sure this is the best solution, but it seems to fix the problem.
Second, this needs to be heavily tested, so don't approve it until you've tested many cases, please.

When modal is not detachable, it use the legacy display system, not flex based. So it calculates the position of the modal based on his window position, then apply a margin to center it. It works, when you don't have scrolled...

For me, the margin trick is not the best solution, so i tried to center the modal by calculating the top property instead (hope what I write is understandable), but with including the scroll position.

This is not a breaking change, but regarding the nature of the bug I think that we need to be careful with this PR.

Et voilà !

## Testcase
Before: [JSFiddle](http://jsfiddle.net/7j38xdbw/1/)
After: [JSFiddle](http://jsfiddle.net/dgzLjxwv/)

## Closes
#1009 
#717

### CODE REVIEW

File: src/definitions/modules/modal.js [hunk 1]
```diff
@@ -806,18 +803,25 @@ $.fn.modal = function(parameters) {
...
-            ;
+            if (!settings.detachable) {
+              $module
+                .css({
+                  top: (!$module.hasClass('aligned') && module.can.fit())
+                    ? parseInt(($(window).height() / 2) + $(document).scrollTop() - ($module.height() - settings.padding))
+                    : $(document).scrollTop() + (settings.padding / 2),
+                  marginLeft: -(module.cache.width / 2)
+                }) 
+              ;
```
Comment (lubber-de) [inline src/definitions/modules/modal.js]: Unfortunately this part is somehow not correctly working when the modal is bigger and the background body has less content
See http://jsfiddle.net/bkh17Lgy/
Without this PR change that example was working http://jsfiddle.net/bkh17Lgy/1/

@prudho Could you please take a look again at this and prepare another PR? 😉

Comment (lubber-de) [reply src/definitions/modules/modal.js]: Opened #1079 for this

**Comment by testinfected** [comment]
@lubber-de We have a use case where we using `detachable:false` and `useFlex: true` to drag the Modal around. We recently upgraded to 2.8.2 and it no longer works.

Any idea on how we could force `useFlex` with `detachable:false` like the old behavior did ?

**Comment by lubber-de** [comment]
@testinfected  You can override the internal method to decide for the flex-setting and always return true:
```javascript
var myModal = $('.ui.modal').modal({
  detachable: false
});
myModal.modal('internal',{
  can: {
    useFlex: function(){
    	return true; 
    }
  }
});
myModal.modal('show');
```

See https://jsfiddle.net/a2ukrjme/1/

**Comment by testinfected** [comment]
Will do that, thanks
