### PR TITLE
fix(dropdown): Clearing multiple selection dropdown supports to prevent onChange callback

### LINKED ISSUE #1781: [Dropdown] Clearing a multiple dropdown ignores preventChangeTrigger setting
# Bug Report

When using the behavior `$('#blah').dropdown('clear',true)` on a dropdown, it's supposed to not fire the dropdown's `onChange` function. However if the dropdown happens to be a multiple dropdown, the `onChange` is instead fired once for every selected option.

## Steps to reproduce
1. Make a multiple select dropdown
2. Init the dropdown, adding an `onChange` function with a console.log or whatever
3. Clear the dropdown with the "preventChangeTrigger" flag set to true (via `$('#blah').dropdown('clear',true)`)

## Expected result
The `onChange` should not be triggered.

## Actual result
The `onChange` is triggered once for every selected element, annihilating the world as we know it.

## Testcase
https://jsfiddle.net/designosis/ob4wLf6h/

## Screenshot
Screen Shot 2020-11-25 at 1 54 51 PM

## Version
2.8.7

## Note
This is perhaps related to but not the same as https://github.com/fomantic/Fomantic-UI/issues/165

### PR DESCRIPTION
**Pull request by ko2in**
## Description
When clearing the selected items from multiple dropdown via `clear` method, the `onChange` callback triggers although the `preventChange` is set as true.

It's because, when the dropdown is multiple selection, the `clear` calls the specific internal method to remove multiple selected items without forwarding the `preventChange` setting which results triggering the `onChange` callback.

This PR makes the `clear` method to call the internal method by passing the `preventChange` setting which supports to prevent triggering the `onChange` callback.

## Testcase
**Bug:** https://jsfiddle.net/ko2in/vadg8nr2/1/

**Fix:** https://jsfiddle.net/ko2in/vadg8nr2/2/

## Screenshot
**Bug:**

Dropdown-Bug

**Fix:**

Dropdown-Fix

## Closes
#1781

### CODE REVIEW

File: src/definitions/modules/dropdown.js [hunk 1]
```diff
@@ -3210,12 +3210,12 @@ $.fn.dropdown = function(parameters) {
...
                 module.remove.message();
                 if(isUserValue) {
-                  module.remove.value(stringValue);
+                  module.remove.value(stringValue, stringValue, module.get.item(stringValue), preventChangeTrigger);
                   module.remove.label(stringValue);
                 }
                 else {
                   // selected will also remove label
-                  module.remove.selected(stringValue);
+                  module.remove.selected(stringValue, module.get.item(stringValue), preventChangeTrigger);
```
Comment (lubber-de) [inline src/definitions/modules/dropdown.js:3218]: Inside the `.remove.selected` function the auto generation of `$selectedItem` is dependent on the `allowAddition` setting. by providing `module.get.item(stringValue)` here directly, this would be ignored and probably won't if `allowAdditions` is true.

If, instead of creating the value by yourself, just provide `false`, this would still work as before (and you dont need to repeat the logic here again) but the additional `preventChangeTrigger` can be provided as awell

```suggestion
                  module.remove.selected(stringValue, false, preventChangeTrigger);
```

**Review by lubber-de — CHANGES_REQUESTED** [review]
Please see my comment

File: src/definitions/modules/dropdown.js (hunk 1 above)
Comment (ko2in) [reply src/definitions/modules/dropdown.js]: Thanks. I updated the PR, please review again.

**Review by ko2in — COMMENTED** [review]
Just pass the `false` to avoid duplicate look up when `allowAdditions` is used.

**Review by lubber-de — APPROVED** [review]
LGTM

**Review by exoego — APPROVED** [review]
LGTM
